openapi: 3.0.0
info:
  title: Game Night API
  description: API for managing Game Night events, users, and games.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Authentication endpoints
  - name: Users
    description: User management endpoints
  - name: Events
    description: Event management endpoints
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      security: []
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
                password:
                  type: string
                  minLength: 8
      responses:
        '201':
          description: User created successfully
        '400':
          description: Validation error
        '409':
          description: Email or username already exists
  /api/auth/login:
    post:
      summary: Login a user
      security: []
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful, returns JWT token
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Invalid credentials
  /api/users:
    get:
      summary: Get all users (Admin only)
      tags:
        - Users
      parameters:
        - name: role
          in: query
          required: false
          description: Filter users by role
          schema:
            type: string
            enum:
              - USER
              - ADMIN
            example: USER
        - name: limit
          in: query
          required: false
          description: Maximum number of users to return
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Non-admin)
  /api/users/me:
    get:
      summary: Get current user profile
      tags:
        - Users
      responses:
        '200':
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
    put:
      summary: Update current user profile
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Validation error
        '401':
          description: Unauthorized
    delete:
      summary: Delete current user account
      tags:
        - Users
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
  /api/users/{id}/role:
    patch:
      summary: Update user role (Admin only)
      tags:
        - Users
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
                  enum:
                    - USER
                    - ADMIN
      responses:
        '200':
          description: Role updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Non-admin)
        '404':
          description: User not found
  /api/events/host:
    get:
      summary: Get events hosted by current user
      tags:
        - Events
      responses:
        '200':
          description: List of hosted events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
  /api/events:
    post:
      summary: Create a new event
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - location
                - eventDate
              properties:
                name:
                  type: string
                location:
                  type: string
                eventDate:
                  type: string
                  format: date-time
                description:
                  type: string
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
  /api/events/{id}:
    get:
      summary: Get event by ID
      tags:
        - Events
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Event ID
      responses:
        '200':
          description: Event found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '401':
          description: Unauthorized
        '404':
          description: Event not found
    put:
      summary: Update an existing event
      tags:
        - Events
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Event ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                eventDate:
                  type: string
                  format: date-time
                description:
                  type: string
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not the host)
        '404':
          description: Event not found
    delete:
      summary: Delete an event
      tags:
        - Events
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Event ID
      responses:
        '204':
          description: Event deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not the host)
        '404':
          description: Event not found
  /api/events/{id}/join:
    post:
      summary: Join an event as the current user
      tags:
        - Events
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Event ID
      responses:
        '200':
          description: Successfully joined event
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: Event not found
        '409':
          description: Already joined event
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
        role:
          type: string
          enum:
            - USER
            - ADMIN
    Event:
      type: object
      required:
        - id
        - name
        - location
        - eventDate
        - hostId
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        location:
          type: string
        eventDate:
          type: string
          format: date-time
        description:
          type: string
        hostId:
          type: string
          format: uuid
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/User'
